version: '3'

services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    postgres:
        image: postgres
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: payment
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

